imports:
    - { resource: tables.yml }

services:
    _defaults:
        autowire: false
        public: false

    avathar.bbdkp.dkp_ledger:
        class: avathar\bbdkp\service\dkp_ledger
        arguments:
            - '@dbal.conn'
            - '@avathar.bbaccounts.service.ledger'
            - '%tables.bbdkp_ledger_link%'
        public: true

    avathar.bbdkp.pool_manager:
        class: avathar\bbdkp\service\pool_manager
        arguments:
            - '@dbal.conn'
            - '@avathar.bbdkp.dkp_ledger'
            - '@user'
            - '%tables.bbdkp_pools%'
        public: true

    avathar.bbdkp.event_manager:
        class: avathar\bbdkp\service\event_manager
        arguments:
            - '@dbal.conn'
            - '@user'
            - '%tables.bbdkp_events%'
            - '%tables.bbdkp_raids%'
        public: true
