imports:
    - { resource: tables.yml }

services:
    _defaults:
        autowire: false
        public: false

    avathar.bbdkp.dkp_ledger:
        class: avathar\bbdkp\service\dkp_ledger
        arguments:
            - '@dbal.conn'
            - '@avathar.bbaccounts.service.ledger'
            - '%tables.bbdkp_ledger_link%'
        public: true

    avathar.bbdkp.pool_manager:
        class: avathar\bbdkp\service\pool_manager
        arguments:
            - '@dbal.conn'
            - '@avathar.bbdkp.dkp_ledger'
            - '@user'
            - '@log'
            - '%tables.bbdkp_pools%'
        public: true

    avathar.bbdkp.event_manager:
        class: avathar\bbdkp\service\event_manager
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@log'
            - '%tables.bbdkp_events%'
            - '%tables.bbdkp_raids%'
        public: true

    avathar.bbdkp.raid_manager:
        class: avathar\bbdkp\service\raid_manager
        arguments:
            - '@dbal.conn'
            - '@avathar.bbdkp.dkp_ledger'
            - '@user'
            - '@log'
            - '%tables.bbdkp_raids%'
            - '%tables.bbdkp_raid_attendees%'
            - '%tables.bbdkp_pools%'
            - '%tables.bbdkp_events%'
            - '%tables.bbdkp_ledger_link%'
        public: true

    avathar.bbdkp.adjustment_manager:
        class: avathar\bbdkp\service\adjustment_manager
        arguments:
            - '@dbal.conn'
            - '@avathar.bbdkp.dkp_ledger'
            - '@user'
            - '@log'
            - '%tables.bbdkp_adjustments%'
            - '%tables.bbdkp_adjustment_recipients%'
            - '%tables.bbdkp_pools%'
            - '%tables.bbdkp_ledger_link%'
        public: true

    avathar.bbdkp.event.log_listener:
        class: avathar\bbdkp\event\log_listener
        arguments:
            - '@user'
        tags:
            - { name: event.listener }
